(define (fib x) (letrec ((fib-iter (lambda (n f1 f2) (if (< n 1) f1 (fib-iter (- n 1) f2 (+ f1  f2))))))(fib-iter x 0 1)))
(console-log "ok")
(define helloworld (string->list "今日は世界\nこの手紙はあなたに見えているでしょうか？"))
(define sec 0.25)
(define (type-text text) (if (null? text) (newline) (begin (sleep sec) (display (car text)) (type-text (cdr text)))))
(type-text helloworld)
(newline)
(define user-msg (read (current-input-port)))
(cond ((= uesr-msg "はい") (display "そうですか"))
      ((= uesr-msg "いいえ") (display "…")))
